- name: "Create a New Host"
  connection: local
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
  - name: Create Custer
    dellemc_pmax_cluster:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        cluster_name: AnsibleCluster
        host_list:
        - AnsibleHost2
        - AnsibleHost1
        state: Create
        host_state: in_cluster
  - name: Add host to Custer
    dellemc_pmax_cluster:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        cluster_name: AnsibleCluster
        host_list:
        - AnsibleHost3
        state: present
        host_state: in_cluster
- name: Remove Host from Custer
    dellemc_pmax_cluster:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        cluster_name: AnsibleCluster
        host_list:
        - AnsibleHost3
        state: present
        host_state: not_in_cluster
  - name: Delete Custer
    dellemc_pmax_cluster:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        cluster_name: AnsibleCluster
        host_list:
        state: absent
        host_state: in_cluster