- name: "Create a Masking View from existing components"
  connection: local
  hosts: localhost
  vars:
    array_id: 000197600156
    password: smc
    sgname: Ansible_SG1
    unispherehost: "192.168.1.1"
    universion: "90"
    user: smc
    verifycert: false

  tasks:
    - name: "Create Masking View for Host Access to storage group volumes"
      dellemc_pmax_maskingview:
        array_id: "{{array_id}}"
        password: "{{password}}"
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        user: "{{user}}"
        verifycert: "{{verifycert}}"
        sgname: "{{sgname}}"
        portgroup_id: "Ansible_PG1"
        host_or_cluster : "AnsibleCluster"
        maskingview_name: "Ansible_MV"
