- name: "Create a New Port Group"
  connection: local
  hosts: localhost
  vars:
    array_id: 000197600156
    password: smc
    unispherehost: "192.168.1.1"
    universion: "90"
    user: smc
    verifycert: false
  tasks:
    - name: "Delete Existing Port Group"
      dellemc_pmax_portgroup:
             unispherehost: "{{unispherehost}}"
             universion: "{{universion}}"
             verifycert: "{{verifycert}}"
             user: "{{user}}"
             password: "{{password}}"
             array_id: "{{array_id}}"
             portgroup_id: "Ansible_PG1"
             action: delete
