- name: "Delete a Host"
  connection: local
  hosts: localhost
  vars:
    array_id: 000197600156
    password: smc
    sgname: Ansible_SG
    unispherehost: "192.168.1.1"
    universion: "90"
    user: smc
    verifycert: false

  tasks:
  - name: Delete Host2
    dellemc_pmax_host:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        host_id: "AnsibleHost1"
        action: delete_host
