- name: "Provision Storage For DB Cluster"
  connection: local
  hosts: localhost
  vars:
    array_id: "000197600156"
    password: "smc"
    sgname: "Ansible_SG1"
    unispherehost: "192.168.1.1"
    universion: "90"
    user: "smc"
    verifycert: false
  tasks:
    - name: "Delete Existing Storage Group"
      dellemc_pmax_storagegroup:
        array_id: "{{array_id}}"
        password: "{{password}}"
        sgname: "{{sgname}}"
        slo: "Diamond"
        srp_id: "SRP_1"
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        user: "{{user}}"
        verifycert: "{{verifycert}}"
        action: "delete"
    - debug: var=storagegroup_detail
