- name: "SRDF Operations Playbook"
  connection: local
  hosts: localhost
  vars_files:
    - vars.yml

  tasks:
    - name: "Establish SRDF Session"
      dellemc_pmax_srdf:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        array_id: "{{array_id}}"
        user: "{{user}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        sgname: SRDF_TEST
        action: Establish
    - debug: var=rdfstate
