- name: "Provision a new storage group"
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
    lun_request:
      - num_vols: 2
        cap_gb: 2
        vol_name: "DATA"
      - num_vols: 3
        cap_gb: 2
        vol_name: "REDO"
  tasks:
    - name: "Create New Storage Group volumes"
      dellemc_pmax_storagegroup:
        array_id: "{{array_id}}"
        password: "{{password}}"
        sgname: "Ansible_SG"
        slo: "Diamond"
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        user: "{{user}}"
        verifycert: "{{verifycert}}"
        luns: "{{lun_request}}"
        state: 'present'
        resize: True
    - debug: var=storagegroup_detail
